### ISSUE TITLE
Commit messages do not have expected expression

### ISSUE THREAD

**Issue by eccles** [JJ/github-pr-contains-action#105]
We use this action to ensure that the link to an Azure issue is present in the commit message.
However there is an easy way to bypass the check:

    submit PR with commit message that does not have the AB#NNNN in the commit message
    the verify link issue check fails
    developer edits the github commit message in the Github UI
    verify link issue now PASSES.
    dev merges the change.
    the commit message on main branch does NOT contain the AB#NNNN link - not good

Please add a setting that ignores the message that is displayed in the Github UI as this seems to be a copy of the commit msg and not the actual commit message.

Our current github action is this:

```yaml
name: "Verify Linked Task"

on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v11
        with:
          github-token: ${{github.token}}
          bodyContains: "AB#\\d{4,5}"
```
