### ISSUE TITLE
WaivedUSers does not work

### ISSUE THREAD

**Issue by eccles** [JJ/github-pr-contains-action#106]
```yaml
name: "Verify Linked Task"

on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v11
        with:
          github-token: ${{github.token}}
          bodyContains: "AB#\\d{4,5}"
          waivedUsers: ["dependabot[bot]"]

```

returns error

 Invalid workflow file

The workflow is not valid. .github/workflows/verify-azure-issue.yml (Line: 14, Col: 24): A sequence was not expected
