### ISSUE TITLE
files env variable is too long

### ISSUE THREAD

**Issue by v1v** [JJ/github-pr-contains-action#119]
https://github.com/JJ/github-pr-contains-action/blob/302a97797f4f1b10bbcddeb9916f39bc45a7c6e7/src/main.ts#L96 is the one that produces the below error

```
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/catalog-info/catalog-info'. Argument list too long
```

When parsing 60 files

<img width="295" alt="image" src="https://github.com/JJ/github-pr-contains-action/assets/2871786/4e07e735-69f7-4629-a3d8-745be7a3b2c0">

**Comment by v1v** [comment]
Given the GitHub workflow:

```yaml
name: "Security downgrade detection"
on:
  pull_request_target:

jobs:
  check-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Check PR content"
        id: "check-security-level"
        continue-on-error: true
        uses: JJ/github-pr-contains-action@releases/v12
        with:
          github-token: ${{github.token}}
          diffContains: 'security_level: test|security_level: low'
      - name: "Remove the label of the PR, if needed"
        if: steps.check-security-level.outcome == 'failure'
        run: gh pr edit $PR_NUMBER --remove-label "security_level:downgrade"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
```

When a PR is created and it contains a few dozens of new files:

```
resources/github/engineering/obs/agent-nodejs-opentracing.yaml
resources/github/engineering/obs/agent-python-benchmarks.yaml
resources/github/engineering/obs/aws-lambda.yaml
...
resources/github/engineering/obs/synthetics-service.yaml
resources/github/engineering/obs/synthetics.yaml
```


Then any steps after using `uses: JJ/github-pr-contains-action@releases/v12` will fail with:

```bash
Run gh pr edit $PR_NUMBER --remove-label "security_level:downgrade"
  gh pr edit $PR_NUMBER --remove-label "security_level:downgrade"
  shell: /usr/bin/bash -e {0}
  env:
    files: [{"chunks":[{"content":"@@ -0,0 +1,32 @@","changes":[{"type":"add","add":true,"ln":1,"content":"+---"},{"type":"add","add":true,"ln":2,"content":"+apiVersion: backstage.io/v1alpha1"},...{"type":"add","add":true,"ln":29,"content":"+        observability-leads:"},{"type":"add","add":true,"ln":30,"content":"+          role: Admin"}],"oldStart":0,"oldLines":0,"newStart":1,"newLines":30}],"deletions":0,"additions":30,"from":"/dev/null","to":"resources/github/engineering/obs/uptime.yaml","new":true,"index":["00000000..0026baf6"]}]
    GH_TOKEN: ***
    PR_NUMBER: ***
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/catalog-info/catalog-info'. Argument list too long
```
