### ISSUE TITLE
Great idea

### ISSUE THREAD

**Issue by paulca99** [JJ/github-pr-contains-action#56]
I'm having a bit of trouble running it though,  I have 2 jobs on my PR action, your action seems to work OK , but always fails at the end  with "Error: Not Found" , is it because I have a 2nd job  ?

```
name: 'Terraform GitHub Actions'
on:
  - pull_request
jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v0
      with:
        github-token: ${{github.token}}
        bodyContains: '[x]'
        bodyDoesNotContain: 'Delete this'
        diffContains: ''
        filesChanged: 1
        linesChanged: 1
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.0
          tf_actions_subcommand: 'fmt'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

![image](https://user-images.githubusercontent.com/19557446/128158077-7ad27ba1-4aa1-4dff-acf3-67565eea3544.png)
