### ISSUE TITLE
"Error: not found" when working with a private repository

### ISSUE THREAD

**Issue by paulbakkerbloom** [JJ/github-pr-contains-action#85]
Hi @JJ,

Unfortunately, your recent changes did not fix my error. I'm working in a private repo.

```
jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v8
        with:
          github-token: ${{github.token}}
          bodyDoesNotContain: ''
          bodyContains: '- [x] blabla'
          diffContains: ''
          filesChanged: 1
          linesChanged: 1
```
             
In the first screenshot I the PR body does indeed not contain the required text. It gives two errors: 

<img width="544" alt="image" src="https://user-images.githubusercontent.com/43469496/214014853-40c89451-326a-48b3-a3a1-4b69168a6ccd.png">

In this screenshot it does, but still gives the second error:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/43469496/214014730-9ec82246-c21f-4076-b151-3b5980a9f7f2.png">
