### ISSUE TITLE
Workflow passing on empty description

### ISSUE THREAD

**Issue by reetika-roy** [JJ/github-pr-contains-action#86]
I have the following workflow
```
name: "Check PR"
on:
  pull_request:
    branches: ["main"]
    paths:
      - path/to/file/**

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@master
        with:
          github-token: ${{github.token}}
          bodyContains: "[blah]"
```
I had a PR description that said `[blah]` and ran the workflow- it was fine. But then I edited it to remove the string and I expect it to fail. The workflow keeps passing even on re-triggering.
